"""File tool participants reach the existing print-start checks and clean."""
import configparser
import importlib.util
from types import SimpleNamespace

import jinja2
import pytest

from lib.paths import ROOT

pytestmark = pytest.mark.static

MODULE = (ROOT / "pkgs/klipper/payload/klipper/klippy/extras/ff_print.py")
MACROS = (ROOT / "pkgs/klipper-config/payload/config/ff-print-macros.cfg")


@pytest.fixture(scope="module")
def ff_print():
    spec = importlib.util.spec_from_file_location("ff_print", MODULE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def gcode_file(tmp_path, field=None, body="T0\nG1 X1 E1\n", header=True,
               name="print.gcode"):
    prefix = ("; HEADER_BLOCK_START\n; generated by OrcaSlicer\n"
              "; filament: %s\n; HEADER_BLOCK_END\n" % field
              if header else "")
    path = tmp_path / name
    path.write_text(prefix + body)
    return path


@pytest.mark.parametrize("field,body,participants,initial", [
    ("1", "T0\nG1 E1\n", [0], 0),
    ("3", "T2\nG1 E1\n", [2], 2),
    ("1,2", "T0\nT1\n", [0, 1], 0),
    ("2,4", "T1\nT3\n", [1, 3], 1),
    ("1,2,3,4", "T0\nT1\nT2\nT3\n", [0, 1, 2, 3], 0),
    # Orca Type 2 tower headers can list participants in priming order.
    ("4,1", "T0\nT3\n", [0, 3], 0),
    ("4,1,4,1", "T0\nT3\n", [0, 3], 0),
])
def test_orca_participants_are_independent_of_initial_tool(
        ff_print, tmp_path, field, body, participants, initial):
    metadata = ff_print._parse_metadata(gcode_file(tmp_path, field, body))
    assert metadata["tools"] == participants
    assert metadata["tool"] == initial


@pytest.mark.parametrize("field", ["1,5", "1,x", "1,", "0,2", "", "1,,2"])
def test_invalid_header_derives_no_tools(ff_print, tmp_path, field):
    body = "T3 ; actual selection\nG1 E1\nT1\n"
    metadata = ff_print._parse_metadata(gcode_file(tmp_path, field, body))
    # A partial list is worse than none, and the body is not scanned instead.
    assert "tools" not in metadata
    assert metadata["tool"] == 3  # Existing first-bare-Tn rule.


def test_missing_header_does_not_scan_tn_commands(ff_print, tmp_path):
    path = gcode_file(tmp_path, body="T0\nG1 E1\nT3\nG1 E1\n", header=False)
    metadata = ff_print._parse_metadata(path)
    assert "tools" not in metadata
    assert metadata["tool"] == 0


def test_header_beyond_bounded_head_is_not_read(ff_print, tmp_path):
    path = tmp_path / "late-header.gcode"
    path.write_bytes(b"; padding\n" * (ff_print.HEAD_BYTES // 10 + 1)
                     + b"; HEADER_BLOCK_START\n; filament: 1\n"
                       b"; HEADER_BLOCK_END\nT2\nT3\n")
    assert "tools" not in ff_print._parse_metadata(path)


def test_only_the_bounded_head_is_read(ff_print, tmp_path, monkeypatch):
    path = gcode_file(tmp_path, body="T1\nT3\n", header=False)
    real_open = open
    reads = []

    class Recording:
        def __init__(self, fh):
            self.fh = fh

        def __enter__(self):
            return self

        def __exit__(self, *_args):
            self.fh.close()
            return False

        def read(self, size):
            reads.append(size)
            return self.fh.read(size)

    monkeypatch.setattr(ff_print, "open",
                        lambda name, mode: Recording(real_open(name, mode)),
                        raising=False)
    ff_print._parse_metadata(path)
    assert reads == [ff_print.HEAD_BYTES]


def test_valid_header_does_not_merge_later_t_selection(ff_print, tmp_path):
    path = gcode_file(tmp_path, "1", "T0\nG1 E1\nT3\nG1 E1\n")
    assert ff_print._parse_metadata(path)["tools"] == [0]


def test_valid_header_does_not_change_independent_initial_tool(ff_print,
                                                                tmp_path):
    path = gcode_file(tmp_path, "1", "T3\nT0\nG1 E1\n")
    metadata = ff_print._parse_metadata(path)
    assert metadata["tools"] == [0]
    assert metadata["tool"] == 3


def test_file_without_header_forwards_initial_tool_only(ff_print, tmp_path):
    path = gcode_file(tmp_path, body="T1\nT3\n", header=False)
    job, scripts = make_job(ff_print, tmp_path)
    job._cmd_start("SDCARD_PRINT_FILE", file_command(path))
    assert scripts[0] == ("before", "FF_BEFORE_PRINT_START "
                          "ORIGIN=SDCARD_PRINT_FILE TOOL=1")
    assert job.get_status(0)["tools"] == []


def make_job(ff_print, tmp_path, origin="SDCARD_PRINT_FILE", on_file=None):
    calls = []
    job = ff_print.FFPrint.__new__(ff_print.FFPrint)
    job.printer = SimpleNamespace(lookup_object=lambda name, default=None:
                                  SimpleNamespace(sdcard_dirname=str(tmp_path)))
    job.gcode = SimpleNamespace(run_script_from_command=lambda script:
                                calls.append(("before", script)))
    job.before_macro = "FF_BEFORE_PRINT_START"
    job.previous_handlers = {origin: on_file or (lambda _gcmd:
                             calls.append(("file", origin)))}
    job.active = False
    return job, calls


def file_command(path):
    return SimpleNamespace(get=lambda key, default="": path.name,
                           get_raw_command_parameters=lambda: path.name)


@pytest.mark.parametrize("origin", ["SDCARD_PRINT_FILE", "M23"])
def test_ff_print_forwards_exact_tools_before_loading_file(ff_print, tmp_path,
                                                            origin):
    path = gcode_file(tmp_path, "4,1", "T0\nT3\n")
    job, calls = make_job(ff_print, tmp_path, origin)

    job._cmd_start(origin, file_command(path))

    assert calls == [
        ("before", "FF_BEFORE_PRINT_START ORIGIN=%s TOOL=0 TOOLS=0,3"
         % origin),
        ("file", origin),
    ]
    assert job.get_status(0)["tools"] == [0, 3]


def test_ff_print_omits_tools_when_file_has_no_header(
        ff_print, tmp_path):
    path = gcode_file(tmp_path, body="M140 S60\n", header=False)
    calls = []
    job = ff_print.FFPrint.__new__(ff_print.FFPrint)
    job.printer = SimpleNamespace(lookup_object=lambda name, default=None:
                                  SimpleNamespace(sdcard_dirname=str(tmp_path)))
    job.gcode = SimpleNamespace(run_script_from_command=calls.append)
    job.before_macro = "FF_BEFORE_PRINT_START"
    job.previous_handlers = {"SDCARD_PRINT_FILE": lambda _gcmd: None}
    gcmd = SimpleNamespace(get=lambda key, default="": path.name)

    job._cmd_start("SDCARD_PRINT_FILE", gcmd)

    assert calls == ["FF_BEFORE_PRINT_START ORIGIN=SDCARD_PRINT_FILE BED=60"]
    assert job.get_status(0)["tools"] == []


@pytest.fixture(scope="module")
def macro_templates():
    cp = configparser.RawConfigParser(
        strict=False, inline_comment_prefixes=(";", "#"))
    cp.read(MACROS)
    env = jinja2.Environment("{%", "%}", "{", "}")
    return {name: env.from_string(cp.get("gcode_macro " + name, "gcode"))
            for name in ("FF_BEFORE_PRINT_START", "START_PRINT",
                         "_FF_NOZZLE_CLEAN")}


def render(template, params, printer, rawparams=""):
    return template.render(params=params, printer=printer,
                           rawparams=rawparams,
                           action_respond_info=lambda _message: "")


def commands(output, prefix):
    return [line.strip() for line in output.splitlines()
            if line.strip().startswith(prefix)]


def test_automatic_preflight_and_clean_use_the_file_participants(macro_templates):
    printer = {"gcode_macro FF_BEFORE_PRINT_START":
               {"prepare": 1, "prepare_on_m23": 0}}
    params = {"ORIGIN": "SDCARD_PRINT_FILE", "TOOL": "0", "TOOLS": "0,3"}
    raw = "ORIGIN=SDCARD_PRINT_FILE TOOL=0 TOOLS=0,3"
    before = render(macro_templates["FF_BEFORE_PRINT_START"], params,
                    printer, raw)
    assert commands(before, "_FF_PREFLIGHT") == [
        "_FF_PREFLIGHT TOOL=0 TOOLS=0,3"]
    assert commands(before, "START_PRINT") == ["START_PRINT " + raw]

    start = render(macro_templates["START_PRINT"], params, printer)
    assert commands(start, "_FF_PREFLIGHT") == [
        "_FF_PREFLIGHT TOOL=0 TOOLS=0,3"]
    assert commands(start, "_FF_NOZZLE_CLEAN") == [
        "_FF_NOZZLE_CLEAN TOOLS=0,3 TEMP=220.0"]
    assert commands(start, "T0") == ["T0"]


def test_explicit_start_print_without_tools_uses_tool_not_published_status(
        macro_templates):
    printer = {"gcode_macro FF_BEFORE_PRINT_START":
               {"prepare": 0, "prepare_on_m23": 0},
               "ff_print": {"active": True, "tools": [0, 3]}}
    params = {"ORIGIN": "SDCARD_PRINT_FILE", "TOOL": "0", "TOOLS": "0,3"}
    before = render(macro_templates["FF_BEFORE_PRINT_START"], params,
                    printer)
    assert commands(before, "_FF_PREFLIGHT") == [
        "_FF_PREFLIGHT TOOL=0 TOOLS=0,3"]
    assert not commands(before, "START_PRINT")

    start = render(macro_templates["START_PRINT"], {"TOOL": "2"}, printer)
    assert commands(start, "_FF_PREFLIGHT") == [
        "_FF_PREFLIGHT TOOL=2 TOOLS=2"]
    assert commands(start, "_FF_NOZZLE_CLEAN") == [
        "_FF_NOZZLE_CLEAN TOOLS=2 TEMP=220.0"]


def test_explicit_start_print_tools_override_published_status(macro_templates):
    printer = {"ff_print": {"active": True, "tools": [0, 2]}}
    start = render(macro_templates["START_PRINT"],
                   {"TOOL": "1", "TOOLS": "1,3"}, printer)
    assert commands(start, "_FF_PREFLIGHT") == [
        "_FF_PREFLIGHT TOOL=1 TOOLS=1,3"]
    assert commands(start, "_FF_NOZZLE_CLEAN") == [
        "_FF_NOZZLE_CLEAN TOOLS=1,3 TEMP=220.0"]


def test_file_a_then_manual_start_without_tools_uses_tool(
        ff_print, tmp_path, macro_templates):
    path = gcode_file(tmp_path, "1,4", "T0\nT3\n", name="a.gcode")
    job, _calls = make_job(ff_print, tmp_path)
    job._cmd_start("SDCARD_PRINT_FILE", file_command(path))
    assert job.get_status(0)["tools"] == [0, 3]
    job.active = False  # Finished jobs retain diagnostic metadata.

    start = render(macro_templates["START_PRINT"], {"TOOL": "2"},
                   {"ff_print": job.get_status(0)})
    assert commands(start, "_FF_NOZZLE_CLEAN") == [
        "_FF_NOZZLE_CLEAN TOOLS=2 TEMP=220.0"]


def test_m23_then_reset_cannot_supply_tools_to_manual_start(
        ff_print, tmp_path, macro_templates):
    path = gcode_file(tmp_path, "1,4", "T0\nT3\n", name="a.gcode")
    selected = {"path": None}
    job, _calls = make_job(ff_print, tmp_path, "M23",
                           on_file=lambda _gcmd: selected.update(path=path))
    job._cmd_start("M23", file_command(path))
    assert selected["path"] == path
    # Pinned virtual_sdcard's SDCARD_RESET_FILE does not notify ff_print;
    # print_stats stays standby because M24 never started the selected file.
    selected["path"] = None
    assert job.get_status(0)["active"]

    start = render(macro_templates["START_PRINT"], {"TOOL": "2"},
                   {"ff_print": job.get_status(0)})
    assert commands(start, "_FF_NOZZLE_CLEAN") == [
        "_FF_NOZZLE_CLEAN TOOLS=2 TEMP=220.0"]


def test_failed_file_selection_cannot_supply_tools_to_later_start(
        ff_print, tmp_path, macro_templates):
    path = gcode_file(tmp_path, "1,4", "T0\nT3\n", name="unselected.gcode")

    def fail(_gcmd):
        raise ValueError("virtual_sdcard rejected the file")

    job, calls = make_job(ff_print, tmp_path, on_file=fail)
    with pytest.raises(ValueError, match="rejected"):
        job._cmd_start("SDCARD_PRINT_FILE", file_command(path))
    assert calls == [("before", "FF_BEFORE_PRINT_START "
                      "ORIGIN=SDCARD_PRINT_FILE TOOL=0 TOOLS=0,3")]
    assert job.get_status(0)["tools"] == [0, 3]

    start = render(macro_templates["START_PRINT"], {"TOOL": "2"},
                   {"ff_print": job.get_status(0)})
    assert commands(start, "_FF_NOZZLE_CLEAN") == [
        "_FF_NOZZLE_CLEAN TOOLS=2 TEMP=220.0"]


def test_file_a_followed_by_successful_file_b_uses_only_b(
        ff_print, tmp_path):
    path_a = gcode_file(tmp_path, "1,4", "T0\nT3\n", name="a.gcode")
    path_b = gcode_file(tmp_path, "2,4", "T1\nT3\n", name="b.gcode")
    job, calls = make_job(ff_print, tmp_path)
    job._cmd_start("SDCARD_PRINT_FILE", file_command(path_a))
    job.active = False  # File A has finished before file B is selected.
    job._cmd_start("SDCARD_PRINT_FILE", file_command(path_b))

    assert [script for kind, script in calls if kind == "before"] == [
        "FF_BEFORE_PRINT_START ORIGIN=SDCARD_PRINT_FILE TOOL=0 TOOLS=0,3",
        "FF_BEFORE_PRINT_START ORIGIN=SDCARD_PRINT_FILE TOOL=1 TOOLS=1,3",
    ]
    assert job.get_status(0)["tools"] == [1, 3]


def test_m23_still_skips_preparation_but_checks_selected_tools(
        macro_templates):
    printer = {"gcode_macro FF_BEFORE_PRINT_START":
               {"prepare": 1, "prepare_on_m23": 0}}
    before = render(macro_templates["FF_BEFORE_PRINT_START"],
                    {"ORIGIN": "M23", "TOOL": "1", "TOOLS": "1,3"},
                    printer)
    assert commands(before, "_FF_PREFLIGHT") == [
        "_FF_PREFLIGHT TOOL=1 TOOLS=1,3"]
    assert not commands(before, "START_PRINT")
    assert not commands(before, "_FF_NOZZLE_CLEAN")


def test_no_file_tools_keeps_manual_start_print_fallback(macro_templates):
    printer = {"ff_print": {"active": False, "tools": []}}
    start = render(macro_templates["START_PRINT"], {"TOOL": "2"}, printer)
    assert commands(start, "_FF_PREFLIGHT") == [
        "_FF_PREFLIGHT TOOL=2 TOOLS=2"]
    assert commands(start, "_FF_NOZZLE_CLEAN") == [
        "_FF_NOZZLE_CLEAN TOOLS=2 TEMP=220.0"]


def test_existing_nozzle_clean_purges_only_the_forwarded_tools(
        macro_templates):
    printer = {"gcode_macro _FF_FILAMENT": {
        "default_temp": 220, "tool_material": ["PLA"] * 4,
        "temps": {"PLA": 220}, "load_feed_thin": 100,
        "load_feed": 200, "purge_length": 50, "purge_fan": .6,
        "purge_retract": 5},
        "configfile": {"settings": {"extruder%d" % n: {
            "nozzle_diameter": .4} for n in range(4)}}}
    for n in range(4):
        printer["tool T%d" % n] = {"extruder": "extruder%d" % n}
    output = render(macro_templates["_FF_NOZZLE_CLEAN"],
                    {"TOOLS": "1,3", "TEMP": "220"}, printer)
    assert commands(output, "_FF_FILAMENT_PREP") == [
        "_FF_FILAMENT_PREP TOOL=1 TEMP=220 ALLOW_PRINTING=1",
        "_FF_FILAMENT_PREP TOOL=3 TEMP=220 ALLOW_PRINTING=1",
    ]
    assert len(commands(output, "G1 E50")) == 2
    assert commands(output, "_FF_NOZZLE_WIPE") == [
        "_FF_NOZZLE_WIPE TOOL=1 TEMP=220",
        "_FF_NOZZLE_WIPE TOOL=3 TEMP=220",
    ]
